const axios = require("axios");

/**
 * Generate and send response to customer for sync failures
 */
async function sendInstructionToCustomer(chatId, syncFailures, teamInstruction) {
  try {
    // Format sync failures for the custom tool
    const formattedFailures = formatSyncFailuresForAI(syncFailures);
    
    console.log(`[periskope] Calling custom tool to generate response...`);

    // Call our custom tool endpoint to generate the response
    const toolResponse = await axios.post(
      'http://localhost:3000/custom-tool/generate-response',
      {
        sync_failures: formattedFailures,
        team_instruction: teamInstruction,
      },
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!toolResponse.data.success) {
      throw new Error(`Tool error: ${toolResponse.data.error}`);
    }

    const generatedMessage = toolResponse.data.message;
    console.log(`[periskope] ✓ Response generated by custom tool`);

    // Now send the generated message to customer
    console.log(`[periskope] Sending generated response to customer — chat_id: ${chatId}`);
    
    const response = await axios.post(
      `${process.env.PERISKOPE_BASE_URL}/message/send`,
      {
        chat_id: chatId,
        message: generatedMessage,
      },
      {
        headers: {
          'Authorization': `Bearer ${process.env.PERISKOPE_API_KEY}`,
          'x-phone': process.env.PERISKOPE_PHONE,
          'Content-Type': 'application/json',
        },
      }
    );

    if (response.status === 200 || response.status === 201) {
      console.log(`[periskope] ✓ Message sent to customer — queue_id: ${response.data.queue_id}`);
      return response.data;
    } else {
      console.error(`[periskope] Failed to send message:`, response.data);
      throw new Error(`Periskope error: ${response.statusText}`);
    }
  } catch (err) {
    console.error(`[periskope] API call failed:`, err.message);
    if (err.response?.status) {
      console.error(`[periskope] Status:`, err.response.status);
      console.error(`[periskope] Data:`, err.response.data);
    }
    throw err;
  }
}

/**
 * Format sync failures for AI prompt
 */
function formatSyncFailuresForAI(rows) {
  if (!rows.length) return "No sync failures found";

  return rows
    .map((r) => {
      const ref = r.reference_id || "—";
      const idname = r.identifier_name || "—";
      const idval = r.identifier_value || "—";
      const err = r.raw_error || "—";
      return `• Bill ID: ${ref}\n  Field: ${idname}\n  Value: ${idval}\n  Error: ${err}`;
    })
    .join("\n\n");
}

module.exports = { sendInstructionToCustomer, formatSyncFailuresForAI };
